#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
picom &
dunst &
mocicon &
flameshot &
feh --bg-fill ~/pics/car.png &
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#2e3440"
bspc config focused_border_color	      "#81a1c1"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^6'
bspc rule -a Spotfy desktop='^10'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
polybar bar
